name: Releases

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Read Configuration
        id: release_config
        uses: muchaszewski/read-json-action@1.0.0
        with:
          path: .github/config/release.json
          properties: "modifiedPlugins"
        env:
          modifiedPlugins: ${{ steps.release_config.outputs.modifiedPlugins }}
      - run: echo ${{ toJSON(env.modifiedPlugins) }}
      - name: installing utilities
        if: true
        working-directory: ./packages/contentstack-utilities
        run: npm install
      - uses: JS-DevTools/npm-publish@v1
        if: ${{ success() &&  true }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/contentstack-utilities/package.json
      - name: installing export
        if: ${{ success() && steps.release_config.outputs.modifiedPlugins.export == true  }}
        working-directory: ./packages/contentstack-export
        run: npm install
      - uses: JS-DevTools/npm-publish@v1
        if: ${{ success() && steps.release_config.outputs.modifiedPlugins.export == true  }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/contentstack-export/package.json
      - name: installing import
        if: ${{ success() && steps.release_config.outputs.modifiedPlugins.import == true  }}
        working-directory: ./packages/contentstack-import
        run: npm install
      - uses: JS-DevTools/npm-publish@v1
        if: ${{ success() && steps.release_config.outputs.modifiedPlugins.import == true  }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/contentstack-import/package.json
